prompts:
  system_prompt: 你是一个财经新闻编辑，要判断新闻类型。
  user_prompt: |
    以下是需要进行分析的信息：

    {}

    请判断该新闻类别属于：收市综评|公司新闻|其他
    请注意，如果新闻类别不属于'收市综评'|'公司新闻'，请选择'其他'。

      例如：'两市全天特大单净流入... 沪深两市全天特大单净流入...'，你的回答：收市综评
      例如：'基金管理公司... ETF产品...'，你的回答：其他

    你的回答：收市综评/公司新闻/其他 
    不要使用其他词汇，只能使用上述三个词汇。
    注意输出语言为中文。
  ds_prompt: |
    以下是需要分析的信息：

    {}

    请判断信息与哪个类别更接近：收市综评|公司新闻|其他

    你的回答：收市综评/公司新闻/其他 
    不要使用其他词汇，只能使用上述三个词汇。
  analysis_template: |
    分析以下文本并归纳其中提及的公司。
    请严格按照以下格式回答问题：

    Text: {}

    涉及公司: <无>|<[公司1], ...>
    简要分析: [你的分析]

    请注意，如果没有提及公司，请填写<无>。
    请严格按照上述格式回答问题。
    要求：请输出JSON格式的答案。
  system_prompt1: 你的任务是判断新闻中是否包含公司。如果有，汇总文档中提及的公司。如果没有，涉及公司的内容为空。
